name: alindor_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Inter_Bold
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf

    - family: Inter_Light
      fonts:
        - asset: assets/fonts/Inter/Inter-Light.ttf

    - family: Inter_Medium
      fonts:
        - asset: assets/fonts/Inter/Inter-Medium.ttf

    - family: Inter_Regular
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf

    - family: Inter_SemiBold
      fonts:
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
